### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by matzar**
Fixed the editor reference image not displaying.

### CODE REVIEW

**Comment by Xerios** [comment]
Way ahead of you 😃

**Comment by matzar** [comment]
Haha I've seen it! Cheers! 😃

**Comment by matzar** [comment]
@Xerios  Do you think we could also add a refernce to my profile? 😄

**Comment by Xerios** [comment]
Second line on https://github.com/Xerios/LazyTheme/blob/master/README.md isn't enough?
Feel free to make a PR or simply tell me what you would like me to write there.

**Comment by matzar** [comment]
Oh sorry didn't see it. I thought about a refernce only on the pink branch but you've done a solid! Thanks! Appracite it! 👍

**Pull request closed without merging**
