### PR TITLE
Add: Pink LazyTheme

### PR DESCRIPTION
**Pull request by matzar**
With help of Justin Meisse we've created Pink LazyTheme! I thought I'd share it with you!

### CODE REVIEW

**Comment by Xerios** [comment]
Ah, nice! Do you have any screenshots by any chance?

It would be nice to have a preview for this color variation in the readme file 😃

**Comment by matzar** [comment]
Sure 😃
pink editor
pink reference

**Comment by Xerios** [comment]
Cheers!

I'll merge it right away

**Comment by matzar** [comment]
Thanks man! 😃

**Pull request merged**
